title: Николай Щепелев
description: Портфолио с проектами Fullstack-разработчика (PHP) - Николай Щепелев
baseurl: '/portfolio-fullstack-php'
url: 'https://shepelevn.github.io'
image: '/assets/images/preview-image.png'

theme: cvless

# site settings
taglong: Fullstack-разработчик (PHP)
tagshort: Fullstack-разработчик (PHP)

# author settings
author:
  name: Николай Щепелев
  email: shepelevnikolay97@gmail.com
photo: assets/images/personal-photo.jpg
address: 
phone: '+7 904 509 32 12'
phone-styled: '+7(904)509-32-12'

# social media links
social:
  github: shepelevn
  gmail: shepelevnikolay97@gmail.com
  hh: https://hh.ru/resume/c5cabd76ff0d2a08380039ed1f61436f525641

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
  - vendor/

gems:
  - jekyll-seo-tag
